"""Add user and subscription models

Revision ID: e8865e8c4182
Revises: ff12241c533b
Create Date: 2025-10-14 22:47:21.425238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8865e8c4182'
down_revision: Union[str, Sequence[str], None] = 'ff12241c533b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('timeframe', sa.String(), nullable=True),
    sa.Column('mae', sa.Float(), nullable=True),
    sa.Column('mse', sa.Float(), nullable=True),
    sa.Column('rmse', sa.Float(), nullable=True),
    sa.Column('rmsse', sa.Float(), nullable=True),
    sa.Column('mape', sa.Float(), nullable=True),
    sa.Column('mase', sa.Float(), nullable=True),
    sa.Column('r2', sa.Float(), nullable=True),
    sa.Column('test_accuracy', sa.Float(), nullable=True),
    sa.Column('recall', sa.Float(), nullable=True),
    sa.Column('precision_rise', sa.Float(), nullable=True),
    sa.Column('precision_fall', sa.Float(), nullable=True),
    sa.Column('f1_score', sa.Float(), nullable=True),
    sa.Column('validation_accuracy', sa.Float(), nullable=True),
    sa.Column('train_accuracy', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metrics_id'), 'metrics', ['id'], unique=False)
    op.create_index(op.f('ix_metrics_ticker'), 'metrics', ['ticker'], unique=False)
    op.create_index(op.f('ix_metrics_timeframe'), 'metrics', ['timeframe'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('provider', sa.Enum('google', 'facebook', name='authprovider'), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.Column('picture', sa.String(), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'canceled', name='subscriptionstatus'), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('last_payment_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.alter_column('ohlc', 'timeframe',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'1d'::character varying"))
    op.alter_column('predictions', 'timeframe',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'1d'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('predictions', 'timeframe',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'1d'::character varying"))
    op.alter_column('ohlc', 'timeframe',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'1d'::character varying"))
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_metrics_timeframe'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_ticker'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_id'), table_name='metrics')
    op.drop_table('metrics')
    # ### end Alembic commands ###
